name: CI
on:
  - push
  - pull_request
jobs:
  test:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v5
      - run: sudo xcode-select -switch /Applications/Xcode_16.4.app
      - run: swift test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: norio-nomura/action-swiftlint@3.2.1
